sonar.projectKey=policy-dekho
sonar.projectName=policy-dekho

sonar.sources=.

# ignore heavy folders
sonar.exclusions=node_modules/**,.next/**

# your local server
sonar.host.url=http://localhost:9000

