sonar.projectKey=Policy-dekho
sonar.projectName=Policy-dekho

sonar.sources=.

# ignore heavy folders
sonar.exclusions=node_modules/**,.next/**

# your local server
sonar.host.url=http://localhost:9000

sonar.eslint.reportPaths=reports/eslint-report.json
# sonar.stylelint.reportPaths=reports/stylelint-report.json
